export type Currency = { code: string; symbol: string; name: string };

export const WORLD_CURRENCIES: Currency[] = [
  { code: 'USD', symbol: '$',    name: 'US Dollar' },
  { code: 'EUR', symbol: '€',    name: 'Euro' },
  { code: 'GBP', symbol: '£',    name: 'British Pound' },
  { code: 'JPY', symbol: '¥',    name: 'Japanese Yen' },
  { code: 'CNY', symbol: '¥',    name: 'Chinese Yuan' },
  { code: 'INR', symbol: '₹',    name: 'Indian Rupee' },
  { code: 'KRW', symbol: '₩',    name: 'South Korean Won' },
  { code: 'AUD', symbol: 'A$',   name: 'Australian Dollar' },
  { code: 'CAD', symbol: 'C$',   name: 'Canadian Dollar' },
  { code: 'CHF', symbol: 'Fr',   name: 'Swiss Franc' },
  { code: 'SGD', symbol: 'S$',   name: 'Singapore Dollar' },
  { code: 'HKD', symbol: 'HK$',  name: 'Hong Kong Dollar' },
  { code: 'TWD', symbol: 'NT$',  name: 'Taiwan Dollar' },
  { code: 'SEK', symbol: 'kr',   name: 'Swedish Krona' },
  { code: 'NOK', symbol: 'kr',   name: 'Norwegian Krone' },
  { code: 'DKK', symbol: 'kr',   name: 'Danish Krone' },
  { code: 'NZD', symbol: 'NZ$',  name: 'New Zealand Dollar' },
  { code: 'MXN', symbol: 'Mex$', name: 'Mexican Peso' },
  { code: 'BRL', symbol: 'R$',   name: 'Brazilian Real' },
  { code: 'ZAR', symbol: 'R',    name: 'South African Rand' },
  { code: 'AED', symbol: 'د.إ',  name: 'UAE Dirham' },
  { code: 'SAR', symbol: '﷼',    name: 'Saudi Riyal' },
  { code: 'QAR', symbol: '﷼',    name: 'Qatari Riyal' },
  { code: 'KWD', symbol: 'KD',   name: 'Kuwaiti Dinar' },
  { code: 'BHD', symbol: 'BD',   name: 'Bahraini Dinar' },
  { code: 'THB', symbol: '฿',    name: 'Thai Baht' },
  { code: 'MYR', symbol: 'RM',   name: 'Malaysian Ringgit' },
  { code: 'IDR', symbol: 'Rp',   name: 'Indonesian Rupiah' },
  { code: 'PHP', symbol: '₱',    name: 'Philippine Peso' },
  { code: 'VND', symbol: '₫',    name: 'Vietnamese Dong' },
  { code: 'PKR', symbol: '₨',    name: 'Pakistani Rupee' },
  { code: 'BDT', symbol: '৳',    name: 'Bangladeshi Taka' },
  { code: 'LKR', symbol: '₨',    name: 'Sri Lankan Rupee' },
  { code: 'NPR', symbol: '₨',    name: 'Nepalese Rupee' },
  { code: 'EGP', symbol: 'E£',   name: 'Egyptian Pound' },
  { code: 'NGN', symbol: '₦',    name: 'Nigerian Naira' },
  { code: 'KES', symbol: 'KSh',  name: 'Kenyan Shilling' },
  { code: 'GHS', symbol: 'GH₵',  name: 'Ghanaian Cedi' },
  { code: 'TZS', symbol: 'TSh',  name: 'Tanzanian Shilling' },
  { code: 'ETB', symbol: 'Br',   name: 'Ethiopian Birr' },
  { code: 'TRY', symbol: '₺',    name: 'Turkish Lira' },
  { code: 'RUB', symbol: '₽',    name: 'Russian Ruble' },
  { code: 'UAH', symbol: '₴',    name: 'Ukrainian Hryvnia' },
  { code: 'PLN', symbol: 'zł',   name: 'Polish Zloty' },
  { code: 'CZK', symbol: 'Kč',   name: 'Czech Koruna' },
  { code: 'HUF', symbol: 'Ft',   name: 'Hungarian Forint' },
  { code: 'RON', symbol: 'lei',  name: 'Romanian Leu' },
  { code: 'ILS', symbol: '₪',    name: 'Israeli Shekel' },
  { code: 'CLP', symbol: 'CLP$', name: 'Chilean Peso' },
  { code: 'COP', symbol: 'COL$', name: 'Colombian Peso' },
  { code: 'ARS', symbol: 'AR$',  name: 'Argentine Peso' },
  { code: 'PEN', symbol: 'S/',   name: 'Peruvian Sol' },
  { code: 'DZD', symbol: 'DA',   name: 'Algerian Dinar' },
  { code: 'MAD', symbol: 'MAD',  name: 'Moroccan Dirham' },
];

export function getCurrencySymbol(code: string): string {
  return WORLD_CURRENCIES.find((c) => c.code === code)?.symbol ?? code;
}
